version: "3.8"

services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-xe
    restart: always
    ports:
      - "1521:1521" # Oracle SQL*Net
      - "5500:5500" # Oracle Enterprise Manager
    environment:
      - ORACLE_PASSWORD=root # Replace with a strong password
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      - ./oracle-data:/opt/oracle/oradata # Persistent data directory for Oracle data files
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'SELECT 1 FROM DUAL;' | sqlplus -s sys/root@//localhost:1521/ORCLCDB as sysdba",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    # stop_grace_period: 1m

volumes:
  oracle-data:
